### ISSUE TITLE
session-header project: MapReactiveSessionRepository -> ReactiveMapSessionRepository

### ISSUE THREAD

**Issue by jim-obrien-orig** [hantsy/spring-reactive-sample#11] opened 2019-02-25 21:45 UTC
In SessionConfig.java MapReactive... does not exist - I'm assuming it's 
```
import org.springframework.session.ReactiveMapSessionRepository;
```

**Comment by hantsy** [comment] 2019-02-26 01:36
Fixed in https://github.com/hantsy/spring-reactive-sample/commit/20e53be34c64c1163a40ea4fe634c349c4813cc5.  This could be caused by a change of the APIs. Thanks for reporting this.

**Closed by hantsy** 2019-02-26 01:36 UTC
